// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class SCCGPIds
{
        public const string achievement_play_120_three = "CgkIwNevl4YbEAIQFQ"; // <GPGSID>
        public const string achievement_three_thousand = "CgkIwNevl4YbEAIQCw"; // <GPGSID>
        public const string achievement_play_30_five = "CgkIwNevl4YbEAIQEg"; // <GPGSID>
        public const string achievement_25000_points = "CgkIwNevl4YbEAIQEQ"; // <GPGSID>
        public const string achievement_100_times = "CgkIwNevl4YbEAIQDg"; // <GPGSID>
        public const string leaderboard_30_second_mode_highscore = "CgkIwNevl4YbEAIQBQ"; // <GPGSID>
        public const string achievement_play_endless = "CgkIwNevl4YbEAIQBw"; // <GPGSID>
        public const string achievement_play_120_ten = "CgkIwNevl4YbEAIQFg"; // <GPGSID>
        public const string achievement_play = "CgkIwNevl4YbEAIQFA"; // <GPGSID>
        public const string achievement_a_thousand = "CgkIwNevl4YbEAIQAg"; // <GPGSID>
        public const string achievement_play_120 = "CgkIwNevl4YbEAIQCQ"; // <GPGSID>
        public const string achievement_7500_points = "CgkIwNevl4YbEAIQEA"; // <GPGSID>
        public const string achievement_500_times = "CgkIwNevl4YbEAIQDw"; // <GPGSID>
        public const string achievement_play_30 = "CgkIwNevl4YbEAIQCA"; // <GPGSID>
        public const string achievement_really_yes_really_10000 = "CgkIwNevl4YbEAIQDA"; // <GPGSID>
        public const string achievement_play_30_fifteen = "CgkIwNevl4YbEAIQEw"; // <GPGSID>
        public const string achievement_10_times = "CgkIwNevl4YbEAIQDQ"; // <GPGSID>
        public const string leaderboard_highscores = "CgkIwNevl4YbEAIQAQ"; // <GPGSID>
        public const string achievement_two_thousand = "CgkIwNevl4YbEAIQCg"; // <GPGSID>
        public const string achievement_login = "CgkIwNevl4YbEAIQAw"; // <GPGSID>
        public const string leaderboard_120_second_mode_highscore = "CgkIwNevl4YbEAIQBg"; // <GPGSID>

}

